/* (c) Copyright Hewlett-Packard Company 2001
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

extern const char
    hwStrDirty[],
    hwStrPos[],
    hwStrDir[],
    hwStrUp[],
    hwStrMatrices[],
    hwStrField[],
    hwStrMirror[],
    hwStrAspect[],
    hwStrPlanes[],
    hwStrJitter[],
    hwStrSkew[],
    hwStrPerspective[],
    hwStrGraphN[],
    hwStrGraphM[],
    hwStrChildren[],
    hwStrParent[],
    hwStrExclude[],
    hwStrRadius[],
    hwStrLatRange[],
    hwStrLonRange[],
    hwStrPosX[],
    hwStrPosY[],
    hwStrWidth[],
    hwStrHeight[],
    hwStrReliefScale[],
    hwStrData[],
    hwStrIndices[],
    hwStrOptFlags[],
    hwStrHasFlags[],
    hwStrHasW[],
    hwStrHasRGB[],
    hwStrHasAlpha[],
    hwStrHasNormals[],
    hwStrHasTangent[],
    hwStrHasST0[], hwStrHasST1[], hwStrHasST2[], hwStrHasST3[],
    hwStrHasST4[], hwStrHasST5[], hwStrHasST6[], hwStrHasST7[],
    hwStrHasR0[], hwStrHasR1[], hwStrHasR2[], hwStrHasR3[],
    hwStrHasR4[], hwStrHasR5[], hwStrHasR6[], hwStrHasR7[],
    hwStrHasQ0[], hwStrHasQ1[], hwStrHasQ2[], hwStrHasQ3[],
    hwStrHasQ4[], hwStrHasQ5[], hwStrHasQ6[], hwStrHasQ7[],
    hwStrHasUV[],
    hwStrVisibility[],
    hwStrFlags[],
    hwStrCookedFlags[],
    hwStrCookedData[],
    hwStrCookedCounts[],
    hwStrRows[],
    hwStrColumns[],
    hwStrComponents[],
    hwStrType[],
    hwStrImage[],
    hwStr__Image[],
    hwStrFileName[],
    hwStrColor[],
    hwStrUncolored[],
    hwStrPositional[],
    hwStrCutoff[],
    hwStrLightExp[],
    hwStrAtten[],
    hwStrScale[],
    hwStrRotate[],
    hwStrTransparency[],
    hwStrSpecColor[],
    hwStrShininess[],
    hwStrBackface[],
    hwStrFlipNormals[],
    hwStrTwoSided[],
    hwStrBright[],
    hwStrInvisible[],
    hwStrWireframe[],
    hwStrTexture[],
    hwStrTextureID[],
    hwStrApply[],
    hwStrBound[],
    hwStrCoordMode[],
    hwStrFilter[],
    hwStrInternalFormat[],
    hwStrSampVert[],
    hwStrBackgroundColor[],
    hwStrAmbientFactor[],
    hwStrAmbientColor[],
    hwStrFog[],
    hwStrFogColor[],
    hwStrFogPlanes[],
    hwStrFogType[],
    hwStrFogDensity[],
    hwStrLighting[],
    hwStrBounds[],
    hwStrPosType[],
    hwStrDirType[],
    hwStrUpType[],
    hwStrTransType[],
    hwStrColorType[],
    hwStrScaleType[],
    hwStrPosParams[],
    hwStrDirParams[],
    hwStrUpParams[],
    hwStrScaleParams[],
    hwStrTransParams[],
    hwStrColorParams[],
    hwStrPosTimes[],
    hwStrDirTimes[],
    hwStrUpTimes[],
    hwStrScaleTimes[],
    hwStrTransTimes[],
    hwStrColorTimes[],
    hwStrLifetime[],
    hwStrOffset[],
    hwStrCycleTime[],
    hwStrDelay[],
    hwStrSurface[],
    hwStrOrient[],
    hwStrExtrude[],
    hwStrAlign[],
    hwStrEquation[],
    hwStrPrunePrim[],
    hwStrTransparentColor[],
    hwStrPosOffset[],
    hwStrNumCycles[],
    hwStrBlend[],
    hwStrPreMult[],
    hwStrShape[],
    hwStrPath[],
    hwStrPathCount[],
    hwStrHasSizes[],
    hwStrHasUp[],
    hwStrHasCaps[],
    hwStrResolution[],
    hwStrMaxDimension[],
    hwStrLOD[],
    hwStrPrimSize[],
    hwStrKeyMapping[],
    hwStrAxisMapping[],
    hwStrActiveColor[],
    hwStrActiveBackground[],
    hwStrActiveTexture[],
    hwStrActive[],
    hwStrExecute[],
    hwStrBorderColor[],
    hwStrActiveBorderColor[],
    hwStrRepeat[],
    hwStrRepeatDelay[],
    hwStrRepeatInterval[],
    hwStrCallback[],
    hwStrEvent[],
    hwStrID[],
    hwStrValue[],
    hwStrFontHeight[],
    hwStrFont[],
    hwStrSpotColor[],
    hwStrNeedleColor[],
    hwStrNeedles[],
    hwStrGaugeRange[],
    hwStrDivisions[],
    hwStrLabel[],
    hwStrPadding[],
    hwStrNeedleLength[],
    hwStrNeedlePos[];
