# Copyright (c) 2012 Ross Cunniff
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

O=OBJ32/
#O=DBG32/
OPTG=
CFLAGS= -m32 -DMAC -DUSE_LIBPNG -DPNG_LITTLE_ENDIAN -DDO_TEST $(OPTG)
LIBS= 

OBJS=	$(O)readpng.o $(O)writepng.o

HDRS=sshzlib.c png_int.h readpng.h

all:	$(O) $(OBJS)

debug:
	make -f Makefile.mac OPTG=-g O=DBG/

$(O)readpng.o:	readpng.c unpack.c filter.c puff.c $(HDRS)
	$(CC) $(CFLAGS) -o $@ -c readpng.c

$(O)writepng.o:	writepng.c unpack.c filter.c puff.c $(HDRS)
	$(CC) $(CFLAGS) -o $@ -c writepng.c

$(O) :
	if [ ! -d $(O) ] ;\
	then \
		mkdir $(O); \
	fi

clean:
	rm -f $(OBJS)
