# Copyright (c) 2012 Ross Cunniff
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

!include <ntwin32.mak>

OPTG=-O2
#OPTG=-Zi

O=OBJ/
#O=DBG/
CFLAGS   = -I./Inc -DWIN32 -DPNG_LITTLE_ENDIAN -nologo -W1 $(OPTG) -Fo$(O)
LIBS     = $(guilibs)
EXES     = readpng.exe
#LOPTS	= -nologo -nodefaultlib:libcd /SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup
LOPTS	= -nologo -nodefaultlib:libcd
#LOPTS = -nologo -nodefaultlib:libcd -debug

I=Inc/
OBJS=	$(O)readpng.obj $(O)writepng.obj

HDRS=puff.h png_int.h

all:	$(O) $(OBJS)

debug:
	nmake /f Makefile.nt OPTG=-Zi \
		LOPTS="-nologo -nodefaultlib:libcd -debug" \
		O=DBG/

$(O)readpng.obj:	readpng.c unpack.c filter.c puff.c $(HDRS)
	$(CC) $(CFLAGS) -c readpng.c

$(O)writepng.obj:	writepng.c unpack.c filter.c puff.c $(HDRS)
	$(CC) $(CFLAGS) -c writepng.c

$(O) :
	if not exist $(*D) md $(*D)

O=

clean:
	for %i in ($(OBJS)) do if exist OBJ\%i          del OBJ\%i

clobber:
	nmake /f Makefile.win clean
	for %i in ($(EXES)) do if exist %i del %i
